#!/bin/sh
set -xa

#################################################################
# 9/20/2009, Julia Zhu   Scripts are modified to be sharable
#                        between EMC and NCO
#         Please note that variable "RUN_ENVIR" is set and used
#         in the development enviroment only.
#################################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}
export SENDECF=${SENDECF:-YES}

###############################
# Specify RUN name
###############################
export NET=verf
export RUN=ens

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = nco ]; then
  if [ $envir != "prod" ] ; then
    export SENDDBN=${SENDDBN:-NO}
    export DBNLOG=${DBNLOG:-YES}
    export DATA_IN=${DATA_IN:-$DATAROOT}
    export COMSREF=${COMSREF:-$(compath.py sref/prod)/sref}
  fi

fi

verf_g2g_ver=${verf_g2g_ver:-v3.1.4}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to $DATAROOT
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" = dev ]    ### For Developers
then
  . /gpfs/dell2/emc/verification/noscrub/Binbin.Zhou/grid2grid/verf_g2g.${verf_g2g_ver}/parm/verf_g2g_prod_config
fi

#if [ $SENDECF = YES ]
#then
#  ecflow_client --init=${ECF_RID}
#fi
#
# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA_IN=${DATA_IN:-$DATAROOT}
export DATA=$DATA_IN/verf_g2g_ens_${cyc}_${envir}.$$

rm -rf $DATA
mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export HOMEverf_g2g=${HOMEverf_g2g:-${NWROOT}/verf_g2g.${verf_g2g_ver}}
export EXECverf_g2g=${EXECverf_g2g:-$HOMEverf_g2g/exec}
export FIXverf_g2g=${FIXverf_g2g:-$HOMEverf_g2g/fix}
export PARMverf_g2g=${PARMverf_g2g:-$HOMEverf_g2g/parm}
export USHverf_g2g=${USHverf_g2g:-$HOMEverf_g2g/ush}

# Run setpdy and initialize PDY variables
setpdy.sh
. $DATA/PDY

export vday=${vday:-$PDYm2}

##################################
# Define model input COMIN
##################################
host=`hostname`
if [ "${host:0:1}" = m ] ; then
 dir=t
elif [  "${host:0:1}" = v ] ; then
 dir=g
fi

  export naefs_ver=${naefs_ver:-v6.0.6}
  export COMRAP=${COMRAP:-$(compath.py rap/prod)/rap}
  export COMSREF=${COMSREF:-$(compath.py sref/prod)/sref}
  export COMNAMNEST=${COMNAMNEST:-$(compath.py nam/prod)/nam}
  export COMHIRESW=${COMHIRESW:-$(compath.py hiresw/prod)/hiresw}
  export COMNAMFIREWX=${COMNAMFIREWX:-$(compath.py nam/prod)/nam}
  export COMNAM=${COMNAM:-$(compath.py nam/prod)/nam}
  export COMMOSAIC=${COMMOSAIC:-$(compath.py hourly/prod/radar)}
  export COMBUFR=${COMBUFR:-$(compath.py hourly/prod)}
  export COMGFS=${COMGFS:-$(compath.py gfs/prod)/gfs}
  export COMHRRR=${COMHRRR:-$(compath.py hrrr/prod)/hrrr}
  export COMGFSANL=${COMGFSANL:-$(compath.py gfs/prod)/gfs}
  export COMGEFS=${COMGEFS:-$(compath.py gefs/prod)/gefs}
  export COMNDAS=${COMNAM:-$(compath.py nam/prod)/nam}
  export COMNAEFS=${COMNAEFS:-$(compath.py naefs/prod)/cmce}
  export COMCMCE=$COMNAEFS
  export AFWADIR=${AFWADIR:-$DCOMROOT/prod}
  export CLAVRDIR=${CLAVRDIR:-$DCOMROOT/prod}
  export FIXGFSCLIM=${FIXGFSCLIM:-$FIXverf_g2g}

##################################
# Define COMIN/COMOUT variables
##################################
export COM_IN=${COM_IN:-$COMROOT/verf/${envir}}
export COM_OUT=${COM_OUT:-$COMROOT/verf/${envir}}

export FCSTDIR=${FCSTDIR:-$COM_OUT/${RUN}}
export OBSVDIR=${OBSVDIR:-$COM_OUT/${RUN}}

export COMIN=$COM_IN/${RUN}.$vday
export COMOUT=$COM_OUT/${RUN}.$vday
export COMVSDB=${COMVSDB:-$COMROOT/verf/${envir}/vsdb/grid2grid}

mkdir -p -m 775 $COMOUT $COMVSDB/${RUN}

env

#######################################################################
# Execute the script.
sh $HOMEverf_g2g/scripts/exverf_g2g_ens.sh.ecf $vday

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

exit 

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

