#!/bin/sh
set -xa

#################################################################
# 9/20/2009, Julia Zhu   Scripts are modified to be sharable
#                        between EMC and NCO
#         Please note that variable "RUN_ENVIR" is set and used
#         in the development enviroment only.
#################################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}
export SENDECF=${SENDECF:-YES}

###############################
# Specify RUN name
###############################
export NET=verf
export RUN=firewx

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -o "$RUN_ENVIR" = para ]; then
  if [ $envir != "prod" ] ; then
    export SENDDBN=${SENDDBN:-NO}
    export jlogfile=${jlogfile:-/com/logs/${envir}/jlogfile}
    export DBNROOT=/nwprod/spa_util/fakedbn
    export DBNLOG=${DBNLOG:-YES}
    export DATA_IN=${DATA_IN:-/tmpnwprd2}
  fi
fi

verf_g2g_ver=${verf_g2g_ver:-v3.0.12}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" = dev ]    ### For Developers
then
  . /gpfs/dell2/emc/verification/noscrub/Binbin.Zhou/grid2grid/verf_g2g.${verf_g2g_ver}/parm/verf_g2g_prod_config
fi

#if [ $SENDECF = YES ]
#then
#  ecflow_client --init=${ECF_RID}
#fi
#
# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA_IN=${DATA_IN:-/tmpnwprd1}
export DATA=$DATA_IN/verf_g2g_firewx_${cyc}_${envir}.$$

rm -rf $DATA
mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.$$}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export HOMEverf_g2g=${HOMEverf_g2g:-/nw${envir}/verf_g2g.${verf_g2g_ver}}
export EXECverf_g2g=${EXECverf_g2g:-$HOMEverf_g2g/exec}
export FIXverf_g2g=${FIXverf_g2g:-$HOMEverf_g2g/fix}
export PARMverf_g2g=${PARMverf_g2g:-$HOMEverf_g2g/parm}
export USHverf_g2g=${USHverf_g2g:-$HOMEverf_g2g/ush}

###################################
# Set up the UTILITIES
###################################
export utilscript=/gpfs/dell1/nco/ops/nwprod/prod_util.v1.1.0/ush

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. $DATA/PDY

#export vday=$PDYm1    #yesterday
export vday=$PDY       #today

##################################
# Define model input COMIN
##################################
export COMNAM=${COMNAM:-/gpfs/gp2/nco/ops/com/nam/prod/nam}
export COMNAMNEST=${COMNAM}
export COMHRRR=${COMHRRR:-/gpfs/hps/nco/ops/com/hrrr/prod/hrrr}
export COMNAMFIREWX=$COMNAM
export COMMOSAIC=${COMMOSAIC:-/gpfs/${dir}p1/nco/ops/com/hourly/prod/radar}
##################################
# Define COMIN/COMOUT variables
##################################
export COM_IN=${COM_IN:-/com/verf/${envir}}
export COM_OUT=${COM_OUT:-/com/verf/${envir}}

export FCSTDIR=${FCSTDIR:-$COM_OUT/${RUN}}
export OBSVDIR=${OBSVDIR:-$COM_OUT/${RUN}}

export COMIN=$COM_IN/${RUN}.$vday
export COMOUT=$COM_OUT/${RUN}.$vday
export COMVSDB=${COMVSDB:-/com/verf/${envir}/vsdb/grid2grid}

mkdir -p -m 775 $COMOUT $COMVSDB/${RUN}

env

#####################################################################################
# Execute the script.  $PDYm2 is running-day since firewx is verified in foreward mode
# $PDYm1 is nextday1,  $PDY(today) is nextday2 
sh $HOMEverf_g2g/scripts/exverf_g2g_firewx.sh.ecf $PDYm2 $PDYm1 $vday

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

#cd $DATA_IN
#if [ ${RM_TMPDIR:-NO} = YES ]; then
#  rm -rf $DATA
#fi

date

