#!/bin/ksh
#
#  This script is to run g2g Fortran executable g2g.x
#  input: user.ctl.$model which was generated by prepg2g.sh
#
#  B. Zhou Nov. 15, 2014: Upgraded to grib2
#
#
set -x

#  arange forecast and observation grib file names ############################

#CLOUDMODEL=$1

 read LINE
 set -A x $LINE
 model=${x[0]}
 YYYYMMDDHH=${x[1]}
 ens=${model:0:4} 
 mdl=${model:0:6}
 bc=${model:0:9}

 #### following are just for tendency:
 if [ -s fcst03.grib.$model ] ; then
  mv fcst03.grib.$model fcst03.grib
  mv fcst03.indx.$model fcst03.indx
  mv obsv03.grib.$model obsv03.grib
  mv obsv03.indx.$model obsv03.indx
 fi

 if [ -s fcst06.grib.$model ] ; then
  mv fcst06.grib.$model fcst06.grib
  mv fcst06.indx.$model fcst06.indx
  mv obsv06.grib.$model obsv06.grib
  mv obsv06.indx.$model obsv06.indx
 fi

 if [ -s fcst12.grib.$model ] ; then
  mv fcst12.grib.$model fcst12.grib
  mv fcst12.indx.$model fcst12.indx
  mv obsv12.grib.$model obsv12.grib
  mv obsv12.indx.$model obsv12.indx   
 fi
  
 if [ -s fcst24.grib.$model ] ; then
  mv fcst24.grib.$model fcst24.grib
  mv fcst24.indx.$model fcst24.indx
  mv obsv24.grib.$model obsv24.grib
  mv obsv24.indx.$model obsv24.indx
 fi
 

# run g2g executable ##############################################                 

if [ $ens = 'gefs' ] || [ $ens = 'naef' ] || [ $ens = 'sref' ] || [ $ens = 'cmce' ] || [ $ens = 'ecme' ] || [ $ens = 'fnmo' ] || [ $ens = 'href' ] ; then   
  $EXECverf_g2g/verf_g2g_grid2grid_grib2 < g2g.ctl.ensemble > output.ensemble
else
  $EXECverf_g2g/verf_g2g_grid2grid_grib2 < g2g.ctl.$model > output.$model
fi

export err=$?; err_chk


if [ $mdl = 'gefs.e' ] ; then
 mv  grid2grid.vsdb GEFS_${YYYYMMDDHH}.vsdb 
elif [ $mdl = 'naefs.' ] ; then
 mv grid2grid.vsdb NAEFS_${YYYYMMDDHH}.vsdb
elif [ $mdl = 'sref.e' ] ; then
 mv grid2grid.vsdb SREF_${YYYYMMDDHH}.vsdb
elif [ $mdl = 'cmce.e' ] ; then
 mv grid2grid.vsdb CMCE_${YYYYMMDDHH}.vsdb
elif [ $mdl = 'fnmoc.' ] ; then
 mv grid2grid.vsdb FNMOC_${YYYYMMDDHH}.vsdb
elif [ $mdl = 'gefs2p' ] ; then
  if [ $bc = 'gefs2p5bc' ] ; then
    mv  grid2grid.vsdb GEFS2P5BC_${YYYYMMDDHH}.vsdb
  else 
    mv  grid2grid.vsdb GEFS2P5_${YYYYMMDDHH}.vsdb
 fi
elif [ $mdl = 'naefs2' ] ; then
  if [ $bc = 'naefs2p5b' ] ; then
    mv grid2grid.vsdb NAEFS2P5BC_${YYYYMMDDHH}.vsdb
  else
    mv grid2grid.vsdb NAEFS2P5_${YYYYMMDDHH}.vsdb
  fi
elif [ $mdl = 'cmce2p' ] ; then
  if [ $bc = 'cmce2p5bc' ] ; then
    mv grid2grid.vsdb CMCE2P5BC_${YYYYMMDDHH}.vsdb
  else
    mv grid2grid.vsdb CMCE2P5_${YYYYMMDDHH}.vsdb
  fi 
elif [ $mdl = 'ecme2p' ] ; then
  if [ $bc = 'ecme2p5bc' ] ; then
    mv grid2grid.vsdb ECME2P5BC_${YYYYMMDDHH}.vsdb
  else
    mv grid2grid.vsdb ECME2P5_${YYYYMMDDHH}.vsdb
  fi
elif [ $mdl = 'fnmoc2' ] ; then
  if [ $bc = 'fnmoc2p5b' ] ; then
    mv grid2grid.vsdb FNMOC2P5BC_${YYYYMMDDHH}.vsdb
  else
    mv grid2grid.vsdb FNMOC2P5_${YYYYMMDDHH}.vsdb
  fi
elif [ $ens = 'href' ] ; then
  mv grid2grid.vsdb HREF_${var}_${YYYYMMDDHH}.vsdb
else
 mv grid2grid.vsdb ${model}_${YYYYMMDDHH}.vsdb
fi

if [ $CLOUDMODEL = 'GEFSCLOUD' ] ; then
  mv  GEFS_${YYYYMMDDHH}.vsdb  ${CLOUDMODEL}_${YYYYMMDDHH}.vsdb
elif [ $CLOUDMODEL = 'CMCECLOUD' ] ; then
  mv CMCE_${YYYYMMDDHH}.vsdb ${CLOUDMODEL}_${YYYYMMDDHH}.vsdb
elif [ $CLOUDMODEL = 'FNMOCCLOUD' ] ; then
  mv FNMOC_${YYYYMMDDHH}.vsdb ${CLOUDMODEL}_${YYYYMMDDHH}.vsdb
fi
 

exit
